'use client'

import Link from 'next/link'
import { useLanguage } from '@/contexts/LanguageContext'

export default function TermsPage() {
  const { language } = useLanguage()
  const it = language === 'it'

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-fuchsia-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <Link href="/" className="text-3xl font-bold text-gradient inline-block mb-6">
            Centyr
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mb-3">
            {it ? 'Termini di Servizio' : 'Terms of Service'}
          </h1>
          <div className="flex items-center justify-center gap-4 text-sm text-gray-500">
            <span>Version 1.0</span>
            <span>·</span>
            <span>{it ? 'Data di entrata in vigore: 22 febbraio 2026' : 'Effective date: February 22, 2026'}</span>
          </div>
        </div>

        {/* Intro box */}
        <div className="bg-amber-50 border-2 border-amber-200 rounded-xl p-5 mb-8 text-sm text-amber-800">
          {it ? (
            <><strong>Leggi attentamente questi Termini.</strong> Creando un account o utilizzando Centyr, confermi di aver letto, compreso e di accettare di essere vincolato dai presenti Termini di Servizio e dalla nostra{' '}
            <Link href="/privacy" className="underline font-semibold">Informativa sulla Privacy</Link>.
            Se non sei d&apos;accordo, non devi utilizzare il servizio.</>
          ) : (
            <><strong>Please read these Terms carefully.</strong> By creating an account or using Centyr, you confirm that you have read, understood, and agree to be bound by these Terms of Service and our{' '}
            <Link href="/privacy" className="underline font-semibold">Privacy Policy</Link>.
            If you do not agree, you must not use the service.</>
          )}
        </div>

        {/* Content */}
        <div className="bg-white/80 backdrop-blur-sm border-2 border-purple-100 rounded-2xl shadow-xl p-8 md:p-12 space-y-8 text-gray-700 leading-relaxed">

          <Section title={it ? '1. Definizioni' : '1. Definitions'}>
            <p>{it ? 'Nei presenti Termini si applicano le seguenti definizioni:' : 'In these Terms, the following definitions apply:'}</p>
            <ul className="mt-3 space-y-2">
              {it ? (
                <>
                  <Def term="&quot;Servizio&quot;">la piattaforma Centyr, inclusa l&apos;applicazione web su centyr.tech, le API e tutte le funzionalità correlate.</Def>
                  <Def term="&quot;Account&quot;">l&apos;account registrato che crei per accedere al Servizio.</Def>
                  <Def term="&quot;Contenuto Utente&quot;">qualsiasi immagine, file o dato che carichi sul Servizio per l&apos;elaborazione.</Def>
                  <Def term="&quot;Output&quot;">immagini elaborate generate dalla nostra pipeline AI a partire dal tuo Contenuto Utente.</Def>
                  <Def term="&quot;Abbonamento&quot;">un piano a pagamento ricorrente che garantisce l&apos;accesso a funzionalità avanzate e limiti di utilizzo più elevati.</Def>
                  <Def term="&quot;Piano Gratuito&quot;">il livello gratuito del Servizio, soggetto a un limite di 3 jobs di elaborazione per mese di calendario.</Def>
                  <Def term="&quot;Noi / Centyr&quot;">il gestore della piattaforma Centyr.</Def>
                </>
              ) : (
                <>
                  <Def term="&quot;Service&quot;">the Centyr platform, including the web application at centyr.tech, the API, and all related features and tooling.</Def>
                  <Def term="&quot;Account&quot;">the registered account you create to access the Service.</Def>
                  <Def term="&quot;User Content&quot;">any images, files, or data you upload to the Service for processing.</Def>
                  <Def term="&quot;Output&quot;">processed images generated by our AI pipeline from your User Content.</Def>
                  <Def term="&quot;Subscription&quot;">a recurring paid plan granting access to enhanced features and higher usage limits.</Def>
                  <Def term="&quot;Free Plan&quot;">the no-cost tier of the Service, subject to a limit of 3 processing jobs per calendar month.</Def>
                  <Def term="&quot;We / Us / Centyr&quot;">the operator of the Centyr platform.</Def>
                </>
              )}
            </ul>
          </Section>

          <Section title={it ? '2. Requisiti di Idoneità' : '2. Eligibility'}>
            <p>
              {it
                ? 'Per utilizzare il Servizio, devi avere almeno 18 anni (o l\'età della maggiore età legale nella tua giurisdizione) ed essere in grado di stipulare un contratto vincolante. Se utilizzi il Servizio per conto di un\'azienda o organizzazione, dichiari di avere l\'autorità di vincolare tale soggetto ai presenti Termini.'
                : 'To use the Service, you must be at least 18 years old (or the age of legal majority in your jurisdiction) and capable of entering into a binding contract. If you are using the Service on behalf of a company or organization, you represent that you have the authority to bind that entity to these Terms.'}
            </p>
            <p className="mt-2">
              {it
                ? 'Il Servizio non è rivolto a minori di 16 anni. Non raccogliamo consapevolmente dati personali di minori.'
                : 'The Service is not directed to children under the age of 16. We do not knowingly collect personal data from minors.'}
            </p>
          </Section>

          <Section title={it ? '3. Registrazione dell\'Account e Sicurezza' : '3. Account Registration and Security'}>
            <p>
              {it
                ? 'Puoi registrarti con un indirizzo email e una password, o tramite un provider OAuth supportato (Google, Apple, GitHub). Accetti di:'
                : 'You may register using an email address and password, or via a supported OAuth provider (Google, Apple, GitHub). You agree to:'}
            </p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              {it ? (
                <>
                  <li>Fornire informazioni di registrazione accurate, aggiornate e complete</li>
                  <li>Mantenere e aggiornare tempestivamente le informazioni del tuo account</li>
                  <li>Mantenere riservate le tue credenziali di accesso e non condividerle con terzi</li>
                  <li>Notificarci immediatamente all&apos;indirizzo <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a> in caso di uso non autorizzato del tuo account</li>
                  <li>Assumerti la responsabilità per tutte le attività che si verificano nel tuo account, che siano autorizzate da te o meno</li>
                </>
              ) : (
                <>
                  <li>Provide accurate, current, and complete registration information</li>
                  <li>Maintain and promptly update your account information</li>
                  <li>Keep your login credentials confidential and not share them with any third party</li>
                  <li>Notify us immediately at <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a> upon discovering any unauthorized use of your account</li>
                  <li>Accept responsibility for all activity that occurs under your account, whether authorized by you or not</li>
                </>
              )}
            </ul>
            <p className="mt-3">
              {it
                ? 'Ci riserviamo il diritto di sospendere o terminare gli account che sembrano essere compromessi o utilizzati fraudolentemente.'
                : 'We reserve the right to suspend or terminate accounts that appear to be compromised or used fraudulently.'}
            </p>
          </Section>

          <Section title={it ? '4. Descrizione del Servizio' : '4. Description of the Service'}>
            <p>
              {it
                ? 'Centyr fornisce una pipeline di elaborazione delle immagini basata sull\'AI che centra, allinea e migliora automaticamente le fotografie di prodotti. Il Servizio accetta caricamenti di immagini tramite l\'interfaccia web o le API, le elabora utilizzando modelli proprietari di visione artificiale e rende i risultati disponibili per il download.'
                : 'Centyr provides an AI-powered image processing pipeline that automatically centers, aligns, and enhances product photographs. The Service accepts image uploads via the web interface or API, processes them using proprietary computer vision models, and makes the results available for download.'}
            </p>
            <p className="mt-2">
              {it
                ? 'Le funzionalità specifiche disponibili dipendono dal tuo piano di abbonamento. La disponibilità delle funzionalità può cambiare nel tempo con un preavviso ragionevole.'
                : 'The specific capabilities available to you depend on your Subscription plan. Feature availability may change over time with reasonable notice.'}
            </p>
          </Section>

          <Section title={it ? '5. Politica di Uso Accettabile' : '5. Acceptable Use Policy'}>
            <p>{it ? 'Puoi utilizzare il Servizio solo per scopi leciti e in conformità con i presenti Termini. Accetti di non:' : 'You may only use the Service for lawful purposes and in accordance with these Terms. You agree not to:'}</p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              {it ? (
                <>
                  <li>Caricare contenuti che violino i diritti di proprietà intellettuale di terzi (copyright, marchi, brevetti, segreti commerciali)</li>
                  <li>Caricare, elaborare o distribuire contenuti illegali, osceni, diffamatori, minacciosi o altrimenti dannosi</li>
                  <li>Tentare di testare la vulnerabilità dei nostri sistemi o reti</li>
                  <li>Utilizzare strumenti automatizzati (bot, scraper, crawler) per accedere al Servizio oltre l&apos;uso API consentito</li>
                  <li>Aggirare, disabilitare o interferire con le funzionalità di sicurezza del Servizio</li>
                  <li>Rivendere, cedere in sublicenza o sfruttare commercialmente il Servizio o i suoi Output senza il nostro previo consenso scritto</li>
                  <li>Utilizzare il Servizio in modo da sovraccaricare, danneggiare o compromettere la nostra infrastruttura</li>
                  <li>Impersonare qualsiasi persona o entità o dichiarare falsamente la propria affiliazione</li>
                </>
              ) : (
                <>
                  <li>Upload content that infringes any third party&apos;s copyright, trademark, patent, trade secret, or other intellectual property rights</li>
                  <li>Upload, process, or distribute content that is illegal, obscene, defamatory, threatening, or otherwise harmful</li>
                  <li>Attempt to probe, scan, or test the vulnerability of our systems or networks</li>
                  <li>Use automated tools (bots, scrapers, crawlers) to access the Service beyond the permitted API use</li>
                  <li>Circumvent, disable, or interfere with security features of the Service</li>
                  <li>Resell, sublicense, or commercially exploit the Service or its Outputs without our prior written consent</li>
                  <li>Use the Service in any manner that could overload, damage, or impair our infrastructure</li>
                  <li>Impersonate any person or entity or misrepresent your affiliation</li>
                </>
              )}
            </ul>
            <p className="mt-3">
              {it
                ? 'Ci riserviamo il diritto di indagare sulle violazioni e adottare le misure appropriate, inclusa la rimozione dei contenuti, la sospensione degli account e il rinvio alle autorità competenti.'
                : 'We reserve the right to investigate violations and take appropriate action, including removal of content, suspension of accounts, and referral to law enforcement.'}
            </p>
          </Section>

          <Section title={it ? '6. Piani di Abbonamento, Prezzi e Fatturazione' : '6. Subscription Plans, Pricing, and Billing'}>
            <p>
              {it ? (
                <>Centyr offre un Piano Gratuito e piani di abbonamento a pagamento. I prezzi, le funzionalità e i limiti degli abbonamenti sono descritti nella <Link href="/pricing" className="text-purple-600 hover:underline">pagina Prezzi</Link>, che può essere aggiornata periodicamente.</>
              ) : (
                <>Centyr offers a Free Plan and paid Subscription plans. Subscription pricing, features, and limits are as described on the <Link href="/pricing" className="text-purple-600 hover:underline">Pricing page</Link>, which may be updated from time to time.</>
              )}
            </p>
            <p className="mt-3"><strong>{it ? '6.1 Ciclo di Fatturazione.' : '6.1 Billing Cycle.'}</strong> {it ? 'Gli abbonamenti a pagamento vengono fatturati mensilmente in anticipo. Il tuo ciclo di fatturazione inizia dalla data del primo abbonamento.' : 'Paid Subscriptions are billed monthly in advance. Your billing cycle begins on the date you first subscribe.'}</p>
            <p className="mt-2"><strong>{it ? '6.2 Elaborazione dei Pagamenti.' : '6.2 Payment Processing.'}</strong> {it ? 'Tutti i pagamenti sono elaborati da Stripe, Inc. Abbonandoti, autorizzi Stripe ad addebitare il tuo metodo di pagamento designato su base ricorrente. Non archiviamo i dati completi della tua carta.' : 'All payments are processed by Stripe, Inc. By subscribing, you authorize Stripe to charge your designated payment method on a recurring basis. We do not store your full card details.'}</p>
            <p className="mt-2"><strong>{it ? '6.3 Imposte.' : '6.3 Taxes.'}</strong> {it ? 'I prezzi sono visualizzati in EUR e possono essere esclusivi dell\'IVA applicabile o di altre imposte, che verranno aggiunte al momento del pagamento in base al tuo indirizzo di fatturazione.' : 'Prices are displayed in EUR and may be exclusive of applicable VAT or other taxes, which will be added at checkout based on your billing address.'}</p>
            <p className="mt-2"><strong>{it ? '6.4 Limiti di Utilizzo.' : '6.4 Usage Limits.'}</strong> {it ? 'Ogni piano include una quota di elaborazione mensile. La quota inutilizzata non si accumula al mese successivo. Al superamento della quota, l\'elaborazione verrà sospesa fino al successivo periodo di fatturazione o finché non effettui un upgrade.' : 'Each plan includes a monthly processing quota. Unused quota does not roll over to the following month. Upon exceeding your quota, processing will be paused until the next billing period or until you upgrade.'}</p>
            <p className="mt-2"><strong>{it ? '6.5 Variazioni di Prezzo.' : '6.5 Price Changes.'}</strong> {it ? 'Ci riserviamo il diritto di modificare i prezzi degli abbonamenti. Forniremo un preavviso di almeno 30 giorni per qualsiasi aumento di prezzo tramite email, e il nuovo prezzo si applicherà al successivo rinnovo.' : 'We reserve the right to change Subscription prices. We will provide at least 30 days\' notice of any price increase via email, and the new price will apply at your next renewal.'}</p>
          </Section>

          <Section title={it ? '7. Prove Gratuite e Offerte Promozionali' : '7. Free Trial and Promotional Offers'}>
            <p>
              {it
                ? 'Potremmo offrire prove gratuite o crediti promozionali a nostra discrezione. Questi sono soggetti a eventuali termini aggiuntivi comunicati al momento dell\'offerta. Ci riserviamo il diritto di modificare o terminare le offerte promozionali in qualsiasi momento senza responsabilità.'
                : 'We may offer free trials or promotional credits at our discretion. These are subject to any additional terms communicated at the time of the offer. We reserve the right to modify or terminate promotional offers at any time without liability.'}
            </p>
          </Section>

          <Section title={it ? '8. Cancellazione e Rimborsi' : '8. Cancellation and Refunds'}>
            <p>
              <strong>{it ? '8.1 Cancellazione.' : '8.1 Cancellation.'}</strong> {it ? 'Puoi cancellare il tuo Abbonamento in qualsiasi momento tramite le impostazioni di fatturazione nel tuo Account. La cancellazione ha effetto al termine del periodo di fatturazione corrente; mantieni l\'accesso al Servizio fino a tale data.' : 'You may cancel your Subscription at any time via the billing settings in your Account. Cancellation takes effect at the end of the current billing period; you retain access to the Service until that date.'}
            </p>
            <p className="mt-2">
              <strong>{it ? '8.2 Politica di Rimborso.' : '8.2 Refund Policy.'}</strong> {it ? (
                <>Offriamo una <strong>garanzia soddisfatti o rimborsati di 30 giorni</strong> su tutti i nuovi abbonamenti a pagamento. Se non sei soddisfatto del Servizio per qualsiasi motivo, contattaci all&apos;indirizzo <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a> entro 30 giorni dal primo pagamento per richiedere un rimborso completo. Questa garanzia si applica una sola volta per cliente e non si applica ai periodi di abbonamento successivi o agli upgrade del piano.</>
              ) : (
                <>We offer a <strong>30-day money-back guarantee</strong> on all new paid Subscriptions. If you are not satisfied with the Service for any reason, contact us at <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a> within 30 days of your first payment to request a full refund. This guarantee applies once per customer and does not apply to subsequent subscription periods or plan upgrades.</>
              )}
            </p>
            <p className="mt-2">
              <strong>{it ? '8.3 Nessun Rimborso per Periodi Parziali.' : '8.3 No Refund for Partial Periods.'}</strong> {it ? 'Salvo quanto previsto dalla clausola 8.2, le quote di abbonamento non sono rimborsabili e non forniamo rimborsi o crediti per mesi parziali.' : 'Except as provided in clause 8.2, subscription fees are non-refundable and we do not provide refunds or credits for partial months.'}
            </p>
          </Section>

          <Section title={it ? '9. Proprietà Intellettuale' : '9. Intellectual Property'}>
            <p>
              <strong>{it ? '9.1 Il Tuo Contenuto.' : '9.1 Your Content.'}</strong> {it ? 'Mantieni tutti i diritti di proprietà sul tuo Contenuto Utente e sugli Output. Caricando contenuti sul Servizio, ci concedi una licenza limitata, non esclusiva e gratuita per archiviare, elaborare e trasmettere i tuoi contenuti nella misura necessaria per fornirti il Servizio. Questa licenza termina quando elimini i tuoi contenuti o chiudi il tuo Account.' : 'You retain all ownership rights to your User Content and Outputs. By uploading content to the Service, you grant us a limited, non-exclusive, royalty-free license to store, process, and transmit your content solely to the extent necessary to provide the Service to you. This license terminates when you delete your content or close your Account.'}
            </p>
            <p className="mt-2">
              <strong>{it ? '9.2 Nostra Proprietà.' : '9.2 Our Property.'}</strong> {it ? 'Il Servizio, incluso il suo software, gli algoritmi, il design visivo, la documentazione e i marchi, è di proprietà di Centyr ed è protetto dalle leggi applicabili sulla proprietà intellettuale. Nessuna disposizione dei presenti Termini trasferisce a te alcun diritto di proprietà sulla nostra proprietà intellettuale.' : 'The Service, including its software, algorithms, visual design, documentation, and trademarks, is owned by Centyr and protected by applicable intellectual property laws. Nothing in these Terms transfers any ownership rights in our intellectual property to you.'}
            </p>
            <p className="mt-2">
              <strong>{it ? '9.3 Nessun Utilizzo per Addestramento.' : '9.3 No Training Use.'}</strong> {it ? 'Non utilizzeremo il tuo Contenuto Utente o gli Output per addestrare, ottimizzare o migliorare i nostri modelli AI senza il tuo consenso esplicito e volontario.' : 'We will not use your User Content or Outputs to train, fine-tune, or improve our AI models without your explicit, opt-in consent.'}
            </p>
          </Section>

          <Section title={it ? '10. Archiviazione ed Eliminazione dei Dati' : '10. Data Storage and Deletion'}>
            <p>
              {it ? (
                <>Le immagini caricate e gli Output elaborati sono archiviati su Amazon Web Services (AWS S3, regione eu-west-3) e sono soggetti a eliminazione automatica dopo <strong>30 giorni</strong> dalla data di creazione. È tua esclusiva responsabilità scaricare e conservare gli Output che desideri mantenere prima della scadenza di questo periodo. Non garantiamo l&apos;archiviazione a lungo termine e non accettiamo alcuna responsabilità per i dati persi per scadenza.</>
              ) : (
                <>Uploaded images and processed Outputs are stored on Amazon Web Services (AWS S3, eu-west-3 region) and are subject to automatic deletion after <strong>30 days</strong> from the date of creation. It is your sole responsibility to download and retain any Outputs you wish to keep before this period expires. We do not guarantee long-term storage and accept no liability for data lost due to expiry.</>
              )}
            </p>
          </Section>

          <Section title={it ? '11. Disponibilità del Servizio e SLA' : '11. Service Availability and SLA'}>
            <p>
              {it
                ? 'Ci impegniamo a mantenere un\'elevata disponibilità, ma non garantiamo il funzionamento ininterrotto o privo di errori del Servizio. Il Servizio è fornito sulla base di un impegno commercialmente ragionevole. La manutenzione pianificata sarà comunicata in anticipo ove possibile. Non siamo responsabili per eventuali perdite derivanti da interruzioni del servizio, perdita di dati o altri disservizi.'
                : 'We aim to maintain high availability but do not guarantee uninterrupted or error-free operation of the Service. The Service is provided on a commercially reasonable efforts basis. Planned maintenance will be communicated in advance where practicable. We are not liable for any losses arising from downtime, data loss, or service interruptions.'}
            </p>
          </Section>

          <Section title={it ? '12. Esclusione di Garanzie' : '12. Disclaimer of Warranties'}>
            <p>
              {it
                ? 'NELLA MISURA MASSIMA CONSENTITA DALLA LEGGE APPLICABILE, IL SERVIZIO È FORNITO "COSÌ COM\'È" E "COME DISPONIBILE" SENZA GARANZIE DI ALCUN TIPO, ESPLICITE O IMPLICITE, INCLUSE MA NON LIMITATE ALLE GARANZIE DI COMMERCIABILITÀ, IDONEITÀ A UNO SCOPO PARTICOLARE, NON VIOLAZIONE O ACCURATEZZA DEI RISULTATI. NON GARANTIAMO CHE IL SERVIZIO SODDISFERÀ LE TUE ESIGENZE O CHE I RISULTATI DELL\'ELABORAZIONE SARANNO PRIVI DI DIFETTI.'
                : 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY OF RESULTS. WE DO NOT WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT PROCESSING RESULTS WILL BE FREE FROM DEFECTS.'}
            </p>
          </Section>

          <Section title={it ? '13. Limitazione di Responsabilità' : '13. Limitation of Liability'}>
            <p>
              {it
                ? 'NELLA MISURA MASSIMA CONSENTITA DALLA LEGGE APPLICABILE, CENTYR NON SARÀ RESPONSABILE PER DANNI INDIRETTI, INCIDENTALI, SPECIALI, CONSEQUENZIALI O PUNITIVI, INCLUSA LA PERDITA DI PROFITTI, LA PERDITA DI DATI O L\'INTERRUZIONE DELL\'ATTIVITÀ, DERIVANTI DAL TUO UTILIZZO O DALL\'IMPOSSIBILITÀ DI UTILIZZARE IL SERVIZIO.'
                : 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CENTYR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, OR BUSINESS INTERRUPTION, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.'}
            </p>
            <p className="mt-2">
              {it
                ? 'IN NESSUN CASO LA NOSTRA RESPONSABILITÀ TOTALE NEI TUOI CONFRONTI PER TUTTE LE RICHIESTE SUPERERÀ IL MAGGIORE TRA (A) L\'IMPORTO CHE CI HAI PAGATO NEI 12 MESI IMMEDIATAMENTE PRECEDENTI LA RICHIESTA, O (B) €100.'
                : 'IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE 12 MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR (B) €100.'}
            </p>
            <p className="mt-2 text-sm text-gray-500">
              {it
                ? 'Nessuna disposizione dei presenti Termini limita la nostra responsabilità per morte o lesioni personali causate da negligenza, frode o qualsiasi altra responsabilità che non può essere esclusa per legge.'
                : 'Nothing in these Terms limits our liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law.'}
            </p>
          </Section>

          <Section title={it ? '14. Indennizzo' : '14. Indemnification'}>
            <p>
              {it
                ? 'Accetti di indennizzare, difendere e tenere indenne Centyr e i suoi dirigenti, amministratori, dipendenti e agenti da e contro qualsiasi reclamo, responsabilità, danno, sentenza e costo (incluse ragionevoli spese legali) derivanti da: (a) il tuo utilizzo del Servizio; (b) il tuo Contenuto Utente; (c) la tua violazione dei presenti Termini; o (d) la tua violazione di qualsiasi legge applicabile o diritti di terzi.'
                : 'You agree to indemnify, defend, and hold harmless Centyr and its officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, and costs (including reasonable legal fees) arising from: (a) your use of the Service; (b) your User Content; (c) your violation of these Terms; or (d) your violation of any applicable law or third-party rights.'}
            </p>
          </Section>

          <Section title={it ? '15. Cessazione' : '15. Termination'}>
            <p>
              <strong>{it ? '15.1 Da parte Tua.' : '15.1 By You.'}</strong> {it ? 'Puoi chiudere il tuo Account in qualsiasi momento contattandoci o utilizzando l\'opzione di eliminazione account nelle impostazioni. La cancellazione dell\'abbonamento è separata dall\'eliminazione dell\'account.' : 'You may close your Account at any time by contacting us or using the account deletion option in settings. Cancellation of your Subscription is separate from account deletion.'}
            </p>
            <p className="mt-2">
              <strong>{it ? '15.2 Da parte Nostra.' : '15.2 By Us.'}</strong> {it ? 'Ci riserviamo il diritto di sospendere o terminare permanentemente il tuo accesso al Servizio, con o senza preavviso, se: (a) violi i presenti Termini; (b) adotti comportamenti fraudolenti o abusivi; o (c) il tuo account rimane inattivo per più di 12 mesi consecutivi.' : 'We reserve the right to suspend or permanently terminate your access to the Service, with or without notice, if you: (a) breach these Terms; (b) engage in fraudulent or abusive behavior; or (c) your account remains inactive for more than 12 consecutive months.'}
            </p>
            <p className="mt-2">
              <strong>{it ? '15.3 Effetti della Cessazione.' : '15.3 Effect of Termination.'}</strong> {it ? 'Alla cessazione, il tuo diritto di utilizzare il Servizio cessa immediatamente. Elimineremo i tuoi dati in conformità alla nostra politica di conservazione. Eventuali obblighi di pagamento in sospeso sopravvivono alla cessazione.' : 'Upon termination, your right to use the Service ceases immediately. We will delete your data in accordance with our retention policy. Any outstanding payment obligations survive termination.'}
            </p>
          </Section>

          <Section title={it ? '16. Forza Maggiore' : '16. Force Majeure'}>
            <p>
              {it
                ? 'Non saremo responsabili per qualsiasi inadempimento o ritardo nell\'esecuzione derivante da cause al di fuori del nostro ragionevole controllo, inclusi eventi naturali, interruzioni di Internet, attacchi informatici, azioni governative, pandemie o guasti infrastrutturali.'
                : 'We shall not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including acts of God, internet outages, cyberattacks, governmental actions, pandemics, or infrastructure failures.'}
            </p>
          </Section>

          <Section title={it ? '17. Modifiche al Servizio e ai Termini' : '17. Modifications to the Service and Terms'}>
            <p>
              {it
                ? 'Ci riserviamo il diritto di modificare, sospendere o interrompere qualsiasi aspetto del Servizio in qualsiasi momento. Potremmo aggiornare periodicamente i presenti Termini. Per modifiche sostanziali, forniremo un preavviso di almeno 14 giorni tramite email o notifica in-app. Il tuo uso continuato del Servizio dopo la data di entrata in vigore costituisce accettazione dei Termini rivisti. Se non sei d\'accordo con le modifiche, devi smettere di utilizzare il Servizio e puoi richiedere un rimborso proporzionale delle eventuali quote prepagate.'
                : 'We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time. We may update these Terms from time to time. For material changes, we will provide at least 14 days\' notice via email or an in-app notification. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms. If you do not agree to the changes, you must stop using the Service and may request a prorated refund of any prepaid fees.'}
            </p>
          </Section>

          <Section title={it ? '18. Legge Applicabile e Risoluzione delle Controversie' : '18. Governing Law and Dispute Resolution'}>
            <p>
              {it
                ? 'I presenti Termini sono regolati e interpretati in conformità alla legge italiana, senza riguardo ai principi di conflitto di leggi. Fatti salvi i diritti dei consumatori applicabili, qualsiasi controversia derivante dai presenti Termini sarà sottoposta alla giurisdizione esclusiva dei tribunali italiani.'
                : 'These Terms are governed by and construed in accordance with the laws of Italy, without regard to conflict of law principles. Subject to applicable consumer protection laws, any dispute arising under these Terms shall be submitted to the exclusive jurisdiction of the courts of Italy.'}
            </p>
            <p className="mt-2">
              {it ? (
                <>Se sei un consumatore dell&apos;UE, puoi anche utilizzare la piattaforma di Risoluzione delle Controversie Online (ODR) della Commissione Europea all&apos;indirizzo <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-purple-600 hover:underline">ec.europa.eu/consumers/odr</a>.</>
              ) : (
                <>If you are an EU consumer, you may also use the European Commission&apos;s Online Dispute Resolution (ODR) platform at <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-purple-600 hover:underline">ec.europa.eu/consumers/odr</a>.</>
              )}
            </p>
          </Section>

          <Section title={it ? '19. Divisibilità e Accordo Completo' : '19. Severability and Entire Agreement'}>
            <p>
              {it
                ? 'Se una qualsiasi disposizione dei presenti Termini risulta inapplicabile, le disposizioni rimanenti continueranno ad avere piena validità ed efficacia. I presenti Termini, insieme all\'Informativa sulla Privacy, costituiscono l\'accordo completo tra te e Centyr in relazione al Servizio e sostituiscono tutti gli accordi precedenti.'
                : 'If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect. These Terms, together with the Privacy Policy, constitute the entire agreement between you and Centyr regarding the Service and supersede all prior agreements.'}
            </p>
          </Section>

          <Section title={it ? '20. Contatti' : '20. Contact'}>
            <p>
              {it ? 'Per domande sui presenti Termini:' : 'For questions about these Terms:'}<br />
              <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a>
            </p>
          </Section>
        </div>

        {/* Footer links */}
        <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-gray-500">
          <Link href="/privacy" className="text-purple-600 hover:text-fuchsia-600 font-semibold transition-colors">
            {it ? 'Informativa sulla Privacy' : 'Privacy Policy'}
          </Link>
          <span className="hidden sm:inline">·</span>
          <Link href="/" className="hover:text-gray-700 transition-colors">
            {it ? '← Torna alla Home' : '← Back to Home'}
          </Link>
        </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold text-gray-900 mb-3 pb-2 border-b border-purple-100">
        {title}
      </h2>
      <div className="space-y-2 text-sm">{children}</div>
    </section>
  )
}

function Def({ term, children }: { term: string; children: React.ReactNode }) {
  return (
    <li className="flex gap-2">
      <span className="font-semibold text-gray-900 whitespace-nowrap" dangerouslySetInnerHTML={{ __html: term }} />
      <span>— {children}</span>
    </li>
  )
}
