import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service - Centyr',
  description: 'Terms and conditions for using Centyr AI product photo processing service.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-fuchsia-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <Link href="/" className="text-3xl font-bold text-gradient inline-block mb-6">
            Centyr
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mb-3">Terms of Service</h1>
          <div className="flex items-center justify-center gap-4 text-sm text-gray-500">
            <span>Version 1.0</span>
            <span>·</span>
            <span>Effective date: February 22, 2026</span>
          </div>
        </div>

        {/* Intro box */}
        <div className="bg-amber-50 border-2 border-amber-200 rounded-xl p-5 mb-8 text-sm text-amber-800">
          <strong>Please read these Terms carefully.</strong> By creating an account or using Centyr, you confirm that you have read, understood, and agree to be bound by these Terms of Service and our{' '}
          <Link href="/privacy" className="underline font-semibold">Privacy Policy</Link>.
          If you do not agree, you must not use the service.
        </div>

        {/* Content */}
        <div className="bg-white/80 backdrop-blur-sm border-2 border-purple-100 rounded-2xl shadow-xl p-8 md:p-12 space-y-8 text-gray-700 leading-relaxed">

          <Section title="1. Definitions">
            <p>In these Terms, the following definitions apply:</p>
            <ul className="mt-3 space-y-2">
              <Def term="&quot;Service&quot;">the Centyr platform, including the web application at centyr.tech, the API, and all related features and tooling.</Def>
              <Def term="&quot;Account&quot;">the registered account you create to access the Service.</Def>
              <Def term="&quot;User Content&quot;">any images, files, or data you upload to the Service for processing.</Def>
              <Def term="&quot;Output&quot;">processed images generated by our AI pipeline from your User Content.</Def>
              <Def term="&quot;Subscription&quot;">a recurring paid plan granting access to enhanced features and higher usage limits.</Def>
              <Def term="&quot;Free Plan&quot;">the no-cost tier of the Service, subject to a limit of 3 processing jobs per calendar month.</Def>
              <Def term="&quot;We / Us / Centyr&quot;">the operator of the Centyr platform.</Def>
            </ul>
          </Section>

          <Section title="2. Eligibility">
            <p>
              To use the Service, you must be at least 18 years old (or the age of legal majority in your jurisdiction) and capable of entering into a binding contract. If you are using the Service on behalf of a company or organization, you represent that you have the authority to bind that entity to these Terms.
            </p>
            <p className="mt-2">
              The Service is not directed to children under the age of 16. We do not knowingly collect personal data from minors.
            </p>
          </Section>

          <Section title="3. Account Registration and Security">
            <p>
              You may register using an email address and password, or via a supported OAuth provider (Google, Apple, GitHub). You agree to:
            </p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Provide accurate, current, and complete registration information</li>
              <li>Maintain and promptly update your account information</li>
              <li>Keep your login credentials confidential and not share them with any third party</li>
              <li>Notify us immediately at <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a> upon discovering any unauthorized use of your account</li>
              <li>Accept responsibility for all activity that occurs under your account, whether authorized by you or not</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend or terminate accounts that appear to be compromised or used fraudulently.
            </p>
          </Section>

          <Section title="4. Description of the Service">
            <p>
              Centyr provides an AI-powered image processing pipeline that automatically centers, aligns, and enhances product photographs. The Service accepts image uploads via the web interface or API, processes them using proprietary computer vision models, and makes the results available for download.
            </p>
            <p className="mt-2">
              The specific capabilities available to you depend on your Subscription plan. Feature availability may change over time with reasonable notice.
            </p>
          </Section>

          <Section title="5. Acceptable Use Policy">
            <p>You may only use the Service for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Upload content that infringes any third party's copyright, trademark, patent, trade secret, or other intellectual property rights</li>
              <li>Upload, process, or distribute content that is illegal, obscene, defamatory, threatening, or otherwise harmful</li>
              <li>Attempt to probe, scan, or test the vulnerability of our systems or networks</li>
              <li>Use automated tools (bots, scrapers, crawlers) to access the Service beyond the permitted API use</li>
              <li>Circumvent, disable, or interfere with security features of the Service</li>
              <li>Resell, sublicense, or commercially exploit the Service or its Outputs without our prior written consent</li>
              <li>Use the Service in any manner that could overload, damage, or impair our infrastructure</li>
              <li>Impersonate any person or entity or misrepresent your affiliation</li>
            </ul>
            <p className="mt-3">
              We reserve the right to investigate violations and take appropriate action, including removal of content, suspension of accounts, and referral to law enforcement.
            </p>
          </Section>

          <Section title="6. Subscription Plans, Pricing, and Billing">
            <p>
              Centyr offers a Free Plan and paid Subscription plans. Subscription pricing, features, and limits are as described on the <Link href="/pricing" className="text-purple-600 hover:underline">Pricing page</Link>, which may be updated from time to time.
            </p>
            <p className="mt-3"><strong>6.1 Billing Cycle.</strong> Paid Subscriptions are billed monthly in advance. Your billing cycle begins on the date you first subscribe.</p>
            <p className="mt-2"><strong>6.2 Payment Processing.</strong> All payments are processed by Stripe, Inc. By subscribing, you authorize Stripe to charge your designated payment method on a recurring basis. We do not store your full card details.</p>
            <p className="mt-2"><strong>6.3 Taxes.</strong> Prices are displayed in EUR and may be exclusive of applicable VAT or other taxes, which will be added at checkout based on your billing address.</p>
            <p className="mt-2"><strong>6.4 Usage Limits.</strong> Each plan includes a monthly processing quota. Unused quota does not roll over to the following month. Upon exceeding your quota, processing will be paused until the next billing period or until you upgrade.</p>
            <p className="mt-2"><strong>6.5 Price Changes.</strong> We reserve the right to change Subscription prices. We will provide at least 30 days' notice of any price increase via email, and the new price will apply at your next renewal.</p>
          </Section>

          <Section title="7. Free Trial and Promotional Offers">
            <p>
              We may offer free trials or promotional credits at our discretion. These are subject to any additional terms communicated at the time of the offer. We reserve the right to modify or terminate promotional offers at any time without liability.
            </p>
          </Section>

          <Section title="8. Cancellation and Refunds">
            <p>
              <strong>8.1 Cancellation.</strong> You may cancel your Subscription at any time via the billing settings in your Account. Cancellation takes effect at the end of the current billing period; you retain access to the Service until that date.
            </p>
            <p className="mt-2">
              <strong>8.2 Refund Policy.</strong> We offer a <strong>30-day money-back guarantee</strong> on all new paid Subscriptions. If you are not satisfied with the Service for any reason, contact us at <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a> within 30 days of your first payment to request a full refund. This guarantee applies once per customer and does not apply to subsequent subscription periods or plan upgrades.
            </p>
            <p className="mt-2">
              <strong>8.3 No Refund for Partial Periods.</strong> Except as provided in clause 8.2, subscription fees are non-refundable and we do not provide refunds or credits for partial months.
            </p>
          </Section>

          <Section title="9. Intellectual Property">
            <p>
              <strong>9.1 Your Content.</strong> You retain all ownership rights to your User Content and Outputs. By uploading content to the Service, you grant us a limited, non-exclusive, royalty-free license to store, process, and transmit your content solely to the extent necessary to provide the Service to you. This license terminates when you delete your content or close your Account.
            </p>
            <p className="mt-2">
              <strong>9.2 Our Property.</strong> The Service, including its software, algorithms, visual design, documentation, and trademarks, is owned by Centyr and protected by applicable intellectual property laws. Nothing in these Terms transfers any ownership rights in our intellectual property to you.
            </p>
            <p className="mt-2">
              <strong>9.3 No Training Use.</strong> We will not use your User Content or Outputs to train, fine-tune, or improve our AI models without your explicit, opt-in consent.
            </p>
          </Section>

          <Section title="10. Data Storage and Deletion">
            <p>
              Uploaded images and processed Outputs are stored on Amazon Web Services (AWS S3, eu-west-3 region) and are subject to automatic deletion after <strong>30 days</strong> from the date of creation. It is your sole responsibility to download and retain any Outputs you wish to keep before this period expires. We do not guarantee long-term storage and accept no liability for data lost due to expiry.
            </p>
          </Section>

          <Section title="11. Service Availability and SLA">
            <p>
              We aim to maintain high availability but do not guarantee uninterrupted or error-free operation of the Service. The Service is provided on a commercially reasonable efforts basis. Planned maintenance will be communicated in advance where practicable. We are not liable for any losses arising from downtime, data loss, or service interruptions.
            </p>
          </Section>

          <Section title="12. Disclaimer of Warranties">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY OF RESULTS. WE DO NOT WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT PROCESSING RESULTS WILL BE FREE FROM DEFECTS.
            </p>
          </Section>

          <Section title="13. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CENTYR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, OR BUSINESS INTERRUPTION, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.
            </p>
            <p className="mt-2">
              IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE 12 MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR (B) €100.
            </p>
            <p className="mt-2 text-sm text-gray-500">
              Nothing in these Terms limits our liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law.
            </p>
          </Section>

          <Section title="14. Indemnification">
            <p>
              You agree to indemnify, defend, and hold harmless Centyr and its officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, and costs (including reasonable legal fees) arising from: (a) your use of the Service; (b) your User Content; (c) your violation of these Terms; or (d) your violation of any applicable law or third-party rights.
            </p>
          </Section>

          <Section title="15. Termination">
            <p>
              <strong>15.1 By You.</strong> You may close your Account at any time by contacting us or using the account deletion option in settings. Cancellation of your Subscription is separate from account deletion.
            </p>
            <p className="mt-2">
              <strong>15.2 By Us.</strong> We reserve the right to suspend or permanently terminate your access to the Service, with or without notice, if you: (a) breach these Terms; (b) engage in fraudulent or abusive behavior; or (c) your account remains inactive for more than 12 consecutive months.
            </p>
            <p className="mt-2">
              <strong>15.3 Effect of Termination.</strong> Upon termination, your right to use the Service ceases immediately. We will delete your data in accordance with our retention policy. Any outstanding payment obligations survive termination.
            </p>
          </Section>

          <Section title="16. Force Majeure">
            <p>
              We shall not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including acts of God, internet outages, cyberattacks, governmental actions, pandemics, or infrastructure failures.
            </p>
          </Section>

          <Section title="17. Modifications to the Service and Terms">
            <p>
              We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time. We may update these Terms from time to time. For material changes, we will provide at least 14 days' notice via email or an in-app notification. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms. If you do not agree to the changes, you must stop using the Service and may request a prorated refund of any prepaid fees.
            </p>
          </Section>

          <Section title="18. Governing Law and Dispute Resolution">
            <p>
              These Terms are governed by and construed in accordance with the laws of Italy, without regard to conflict of law principles. Subject to applicable consumer protection laws, any dispute arising under these Terms shall be submitted to the exclusive jurisdiction of the courts of Italy.
            </p>
            <p className="mt-2">
              If you are an EU consumer, you may also use the European Commission's Online Dispute Resolution (ODR) platform at <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-purple-600 hover:underline">ec.europa.eu/consumers/odr</a>.
            </p>
          </Section>

          <Section title="19. Severability and Entire Agreement">
            <p>
              If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect. These Terms, together with the Privacy Policy, constitute the entire agreement between you and Centyr regarding the Service and supersede all prior agreements.
            </p>
          </Section>

          <Section title="20. Contact">
            <p>
              For questions about these Terms:<br />
              <a href="mailto:support@centyr.tech" className="text-purple-600 hover:underline">support@centyr.tech</a>
            </p>
          </Section>
        </div>

        {/* Footer links */}
        <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-gray-500">
          <Link href="/privacy" className="text-purple-600 hover:text-fuchsia-600 font-semibold transition-colors">
            Privacy Policy
          </Link>
          <span className="hidden sm:inline">·</span>
          <Link href="/" className="hover:text-gray-700 transition-colors">
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold text-gray-900 mb-3 pb-2 border-b border-purple-100">
        {title}
      </h2>
      <div className="space-y-2 text-sm">{children}</div>
    </section>
  )
}

function Def({ term, children }: { term: string; children: React.ReactNode }) {
  return (
    <li className="flex gap-2">
      <span className="font-semibold text-gray-900 whitespace-nowrap" dangerouslySetInnerHTML={{ __html: term }} />
      <span>— {children}</span>
    </li>
  )
}
